import { mdsvex, escapeSvelte } from 'mdsvex';
import { createHighlighter } from 'shiki';
import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex-svelte';
import rehypeCitation from 'rehype-citation';

const theme = 'monokai';
const highlighter = await createHighlighter({
	themes: [theme],
	langs: ['javascript', 'typescript', 'cpp', 'c', 'python', 'bash', 'markdown']
});

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://svelte.dev/docs/kit/integrations
	// for more information about preprocessors
	preprocess: [
		vitePreprocess(),
		{
			// Expand Obsidian-style embeds (as authored in nb) into HTML before
			// mdsvex runs. Assets resolve to /media/<file>, served from static/media/.
			//   ![[pic.png]]             image (png | jpg | jpeg | gif | svg | webp | avif)
			//   ![[pic.png|320]]         image at a pixel width
			//   ![[pic.png|a caption]]   image with a <figcaption>
			//   ![[notes.pdf]]           inline PDF viewer + "open" link
			//   ![](youtube watch url)   embedded video
			markup: ({ content, filename }) => {
				if (!filename?.endsWith('.md')) return { code: content };

				// Raster refs resolve to the optimised .webp the build generates
				// (scripts/optimize-images.mjs); vectors/gifs are left as-is.
				const toWebp = (p) => p.replace(/\.(png|jpe?g)$/i, '.webp');

				const transformEmbeds = (text) =>
					text
						// Images — ![[file.ext]] with an optional |width (numeric) or |caption
						.replace(
							/!\[\[\s*([^|\]]+?\.(?:png|jpe?g|gif|svg|webp|avif))\s*(?:\|\s*([^\]]+?)\s*)?\]\]/gi,
							(_, file, alias) => {
								const src = toWebp(`/media/${file}`);
								if (alias && /^\d+$/.test(alias))
									return `<img src="${src}" alt="${file}" style="width:${alias}px;max-width:100%" />`;
								if (alias)
									return `<figure><img src="${src}" alt="${alias}" /><figcaption>${alias}</figcaption></figure>`;
								return `<img src="${src}" alt="${file}" />`;
							}
						)
						// PDFs — ![[file.pdf]] with an optional |label
						.replace(
							/!\[\[\s*([^|\]]+?\.pdf)\s*(?:\|\s*([^\]]+?)\s*)?\]\]/gi,
							(_, file, alias) => {
								const src = `/media/${file}`;
								const label = alias || file;
								return `<figure class="pdf-embed"><iframe src="${src}" title="${label}" loading="lazy"></iframe><figcaption><a href="${src}" target="_blank" rel="noreferrer">Open ${label} ↗</a></figcaption></figure>`;
							}
						)
						// YouTube — ![](https://www.youtube.com/watch?v=ID)
						.replace(
							/!\[\]\(https:\/\/www\.youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})\)/g,
							`<div class="video-container"><iframe src="https://www.youtube.com/embed/$1" title="YouTube video" frameborder="0" allowfullscreen></iframe></div>`
						);

				// Only transform outside code, so ![[...]] can be shown literally in a
				// fenced or inline code span. Splitting on a capturing group keeps the
				// code spans as odd-indexed segments, which are left untouched.
				content = content
					.split(/(```[\s\S]*?```|`[^`\n]*`)/g)
					.map((seg, i) => (i % 2 === 0 ? transformEmbeds(seg) : seg))
					.join('');

				return { code: content };
			}
		},
		mdsvex({
			extensions: ['.md'],

			highlight: {
				highlighter: async (code, lang = 'text') => {
					// Fall back to plaintext for any language we haven't loaded, so an
					// unknown ```lang fence degrades gracefully instead of failing the build.
					let highlighted;
					try {
						highlighted = highlighter.codeToHtml(code, { lang, theme });
					} catch {
						highlighted = highlighter.codeToHtml(code, { lang: 'text', theme });
					}
					return `{@html \`${escapeSvelte(highlighted)}\` }`;
				}
			},

			remarkPlugins: [remarkMath],
			rehypePlugins: [
				// Pandoc-style @citekey citations -> formatted inline cites + an
				// auto-generated bibliography, resolved against src/content/references.bib.
				// That .bib is GENERATED by scripts/sync-citations.mjs (predev/prebuild):
				// it pulls each cited key from Better BibTeX (Zotero) — don't hand-edit it.
				[
					rehypeCitation,
					{
						bibliography: 'src/content/references.bib',
						path: process.cwd(),
						// IEEE isn't one of rehype-citation's built-ins (apa/vancouver/
						// harvard1/mla/chicago), so point at the CSL file vendored in the repo.
						csl: 'src/content/ieee.csl',
						linkCitations: true
					}
				],
				rehypeKatex
			]
		})
	],

	kit: {
		// adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
		// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
		// See https://svelte.dev/docs/kit/adapters for more information about adapters.
		adapter: adapter({
			pages: 'docs',
			assets: 'docs',
			// The posts/projects [slug] routes are 'auto' so a prod build with no
			// non-example content yields zero pages without erroring. Real slugs are
			// still prerendered explicitly via each route's entries(); unprerendered
			// (i.e. example) URLs simply 404 on the static host, which is intended.
			strict: false,
		}),
	},

	extensions: ['.svelte', '.md']
};

export default config;
